const villes = [
	/*
	['Paris', 'Métropole du Grand Paris'],
	['Marseille', 'Aix-Marseille-Provence'],
	['Lyon', 'Métropole de Lyon'],
	['Toulouse', 'Toulouse Métropole'],
	['Nice', "Nice Côte d'Azur"],
	['Nantes', 'Nantes Métropole'],
	['Montpellier', 'Montpellier Méditerranée Métropole'],
	['Strasbourg', 'Strasbourg Eurométropole'],
	['Bordeaux', 'Bordeaux Métropole'],
	['Nancy', 'Métropole du Grand Nancy'],
	['Metz', 'Metz Métropole'],
	['Rouen', 'Métropole Rouen Normandie'],
	['Lille', 'Métropole Européenne de Lille'],
	['Rennes', 'Rennes Métropole'],
	['Orléans', 'Orléans Métropole'],
	'Reims',
	['Saint-Étienne', 'Saint-Étienne Métropole'],
	'Le Havre',
	*/
	['Tours', 'Tours Métropole Val de Loire'],
	['Toulon', 'Métropole Toulon-Provence-Méditerranée'],
	['Grenoble', 'Grenoble-Alpes Métropole'],
	['Dijon', 'Dijon Métropole'],
	'Angers',
	'Nîmes',
	'Villeurbanne',
	'Aix-en-Provence',
	'Le Mans',
	['Clermont-Ferrand', 'Clermont Auvergne Métropole'],
	['Brest', 'Brest Métropole'],
]

export default villes
